### ISSUE TITLE
hard coded image file for background not in repo

### ISSUE THREAD

**Issue by jdbishop** [ghl-wang/LFA_GUI#1]
Traceback (most recent call last):
  File "c:/Software/GitHub/LFA_GUI/main.py", line 312, in <module>
    app = Application(root, background=BACKGROUND)
  File "c:/Software/GitHub/LFA_GUI/main.py", line 252, in __init__
    bgimg = Image.open(path)
  File "C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\PIL\Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'front.png'

**Comment by ghl-wang** [comment]
image has been uploaded.
